### ISSUE TITLE
Voyant Tools title on screen  but application does not render afterwards

### ISSUE THREAD

**Issue by pguerr061703** [sgsinclair/VoyantServer#13]
Hi,
I installed Voyant Tools 2.1 on my Redhat Virtual server.  The install directory is /opt/VoyantServer 2_1
Since I have other applications using port 80 on this server, I configured Voyant to run on port 8888 in server settings.txt file and configured httpd.conf to redirect all traffic listening on port 8888 to redirect to 80 (So the users of Voyant can just type voyant.ace.fordham.edu  in instead of voyant.ace.fordham.edu:8888).  This worked partially as when I type in http://voyant.ace.fordham.edu, the only thing on the screen is the title "Voyant Tools" on the left corner of the screen.
However if I type ace-admin01.ds.fordham.edu:8888 (this is the localhost), Voyant comes up FINE in its entirety...I wonder what I am doing wrong.  The PassThru in httpd is working...but it seems Voyant doesnt finish loading when I go to voyant.ace.fordham.edu. 

My httpd.conf is as follows:

<VirtualHost *:80>
     ServerName voyant.ace.fordham.edu
     DocumentRoot /opt/VoyantServer2_1/_app/
     ProxyRequests Off
     ProxyPreserveHost On
     <Proxy *>
          Order deny,allow
          Allow from all
     </Proxy>
     ProxyPass / http://localhost:8888
     ProxyPassReverse / http://localhost:8888
     <Location /opt/VoyantServer2_1/_app>
          Order deny,allow
          Allow from all
     </Location>
</VirtualHost>

**Comment by sgsinclair** [comment]
When I try http://voyant.ace.fordham.edu I see a generic Apache page, could you please set it back to point to the proxied server so I can have a look from here?

**Comment by pguerr061703** [comment]
This is only available inside Fordham's network (internally). I would have to get a firewall rule to open 8888 on the outside. Can you help me via a Teamviewer of WebEx ? I have an account for both.

thanks

**Comment by sgsinclair** [comment]
Could you please attach here the source HTML that appears at the voyant.ace address? Also, do you see any errors in the browser console?

**Comment by pguerr061703** [comment]
Html page source below (from http://voyant.ace.fordham.edu) 
Only thing that shows on the screen is the words "Voyant Tools" on the upper left corner
When I type: http://ace-admin01.ds.fordham.edu:8888  - Voyant WORKS in its entirety

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="shortcut icon" type="image/ico" href="/resources/voyant/favicon.ico" />

<script type="text/javascript" src="/resources/ext/6.0.1/ext-all.js"></script>

<script type="text/javascript" src="/resources/ext/6.0.1/charts.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/ext/6.0.1/charts-all.css" />

<script type="text/javascript" src="/resources/ext/6.0.1/theme-crisp/theme-crisp.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/ext/6.0.1/theme-crisp/resources/theme-crisp-all_1.css" />
<link rel="stylesheet" type="text/css" href="/resources/ext/6.0.1/theme-crisp/resources/theme-crisp-all_2.css" />



<script type="text/javascript" src="/resources/jquery/current/jquery.min.js"></script>

<script type="text/javascript" src="/resources/jquery/current/jquery-ui.min.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/jquery/current/jquery-ui.min.css" />
<link rel="stylesheet" type="text/css" href="/resources/jquery/current/jquery-ui.theme.min.css" />



<script type="text/javascript" src="/resources/d3/current/d3.min.js"></script>

<script type="text/javascript" src="/resources/cirrus/html5/d3.layout.cloud.js"></script>



<script type="text/javascript" src="/resources/visjs/vis.min.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/visjs/vis.min.css" />



<link rel="stylesheet" type="text/css" href="/resources/fontawesome/current/css/font-awesome.min.css" />

<link rel="stylesheet" type="text/css" href="/resources/css/styles.css" />

<script type="text/javascript" src="/resources/voyant/current/voyant.jsp?v=6"></script>

<script type="text/javascript" src="/resources/voyant/current/voyant-locale.jsp?v=6&lang=en"></script>



<script>
Ext.onReady(function(){
    Ext.application({
        extend : 'Voyant.VoyantDefaultApp',
        name: 'VoyantDefaultApp',
        config: {
            baseUrl: 'http://voyant.ace.fordham.edu:80/',
            version: '2.1',
            build: ''           
        },
        launch: function() {
            var me = this;
            this.callParent(arguments);
            if (window.location.hostname==='beta.voyant-tools.org') {
                var viewport = this.getViewport();
                viewport.mask();
                Ext.create('Ext.window.Window', {
                    title: 'Voyant Tools 2.0',
                    margin: '20 200 10 10',
                    modal: true,
                    maxWidth: 420,
                    layout: 'fit',
                    items: [{
                        margin: '10 5 3 10',
                        layout: 'fit',
                        scrollable: true,
                        html: "<p style='color: red; font-weight: bold;'>Please note that this is the beta server and you should not count on corpora persisting (for bookmarks, embedding, etc.)."
                    }],
                    bbar: [{
                        xtype: 'button',
                        glyph: 'xf00c@FontAwesome',
                        ui: 'default',
                        width: '100%',
                        scale: 'medium',
                        text: 'Continue',
                        handler: function(btn) {
                            btn.up('window').close();
                        }
                    }],
                    listeners: {
                        beforerender: function(panel) {
                            panel.items.get(0).setMaxHeight(me.getApplication().getViewport().getHeight()-150);
                        },
                        close: function(panel) {
                            viewport.unmask();
                        }
                    }
                }).show();
            }
        }
    });
});
</script>

<title>Voyant Tools</title>

<script>
if (Ext) {
    Ext.onReady(function () {
        Ext.get("pageloading").hide();
    });
}
</script>

</head>
<body>

<div id="pageloading"><span class="title">Voyant Tools</span><span class="logo"></span></div>

<script type="text/javascript">
var isLocalHost = window.location.hostname=='localhost' || window.location.hostname=='127.0.0.1';
if (!isLocalHost) { // only do google analytics if we're apparently not running locally
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
}
</script>

<script type="text/javascript">
if (!isLocalHost) {
    try {
    var pageTracker = _gat._getTracker("UA-957935-3");
    pageTracker._trackPageview();
    } catch(err) {}
}</script>

</body>
</html>

**Comment by pguerr061703** [comment]
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="shortcut icon" type="image/ico" href="/resources/voyant/favicon.ico" />

<script type="text/javascript" src="/resources/ext/6.0.1/ext-all.js"></script>

<script type="text/javascript" src="/resources/ext/6.0.1/charts.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/ext/6.0.1/charts-all.css" />

<script type="text/javascript" src="/resources/ext/6.0.1/theme-crisp/theme-crisp.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/ext/6.0.1/theme-crisp/resources/theme-crisp-all_1.css" />
<link rel="stylesheet" type="text/css" href="/resources/ext/6.0.1/theme-crisp/resources/theme-crisp-all_2.css" />



<script type="text/javascript" src="/resources/jquery/current/jquery.min.js"></script>

<script type="text/javascript" src="/resources/jquery/current/jquery-ui.min.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/jquery/current/jquery-ui.min.css" />
<link rel="stylesheet" type="text/css" href="/resources/jquery/current/jquery-ui.theme.min.css" />



<script type="text/javascript" src="/resources/d3/current/d3.min.js"></script>

<script type="text/javascript" src="/resources/cirrus/html5/d3.layout.cloud.js"></script>



<script type="text/javascript" src="/resources/visjs/vis.min.js"></script>

<link rel="stylesheet" type="text/css" href="/resources/visjs/vis.min.css" />



<link rel="stylesheet" type="text/css" href="/resources/fontawesome/current/css/font-awesome.min.css" />

<link rel="stylesheet" type="text/css" href="/resources/css/styles.css" />

<script type="text/javascript" src="/resources/voyant/current/voyant.jsp?v=6"></script>

<script type="text/javascript" src="/resources/voyant/current/voyant-locale.jsp?v=6&lang=en"></script>



<script>
Ext.onReady(function(){
    Ext.application({
        extend : 'Voyant.VoyantDefaultApp',
        name: 'VoyantDefaultApp',
        config: {
            baseUrl: 'http://voyant.ace.fordham.edu:80/',
            version: '2.1',
            build: ''           
        },
        launch: function() {
            var me = this;
            this.callParent(arguments);
            if (window.location.hostname==='beta.voyant-tools.org') {
                var viewport = this.getViewport();
                viewport.mask();
                Ext.create('Ext.window.Window', {
                    title: 'Voyant Tools 2.0',
                    margin: '20 200 10 10',
                    modal: true,
                    maxWidth: 420,
                    layout: 'fit',
                    items: [{
                        margin: '10 5 3 10',
                        layout: 'fit',
                        scrollable: true,
                        html: "<p style='color: red; font-weight: bold;'>Please note that this is the beta server and you should not count on corpora persisting (for bookmarks, embedding, etc.)."
                    }],
                    bbar: [{
                        xtype: 'button',
                        glyph: 'xf00c@FontAwesome',
                        ui: 'default',
                        width: '100%',
                        scale: 'medium',
                        text: 'Continue',
                        handler: function(btn) {
                            btn.up('window').close();
                        }
                    }],
                    listeners: {
                        beforerender: function(panel) {
                            panel.items.get(0).setMaxHeight(me.getApplication().getViewport().getHeight()-150);
                        },
                        close: function(panel) {
                            viewport.unmask();
                        }
                    }
                }).show();
            }
        }
    });
});
</script>

<title>Voyant Tools</title>

<script>
if (Ext) {
    Ext.onReady(function () {
        Ext.get("pageloading").hide();
    });
}
</script>

</head>
<body>

<div id="pageloading"><span class="title">Voyant Tools</span><span class="logo"></span></div>

<script type="text/javascript">
var isLocalHost = window.location.hostname=='localhost' || window.location.hostname=='127.0.0.1';
if (!isLocalHost) { // only do google analytics if we're apparently not running locally
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
}
</script>

<script type="text/javascript">
if (!isLocalHost) {
    try {
    var pageTracker = _gat._getTracker("UA-957935-3");
    pageTracker._trackPageview();
    } catch(err) {}
}</script>

</body>
</html>

**Comment by pguerr061703** [comment]
[Page_Source_From_Voyant.ace.fordham.edu.txt](https://github.com/sgsinclair/VoyantServer/files/558699/Page_Source_From_Voyant.ace.fordham.edu.txt)

**Comment by pguerr061703** [comment]
I attached file Page_Source_From_Voyant.ace.fordham.edu

**Comment by sgsinclair** [comment]
The attachment doesn't seem to work, maybe email me, same user handle as Github, at gmail.

**Comment by pguerr061703** [comment]
sent to you via email

**Comment by sgsinclair** [comment]
issue resolved with a proxy tweak
