### ISSUE TITLE
TermsRadio not handling apostrophes?

### ISSUE THREAD

**Issue by jaguillette** [sgsinclair/VoyantServer#23]
I've been trying out Voyant, and I've been running into a strange problem in TermsRadio. When i click on a term with an apostrophe, the term appears in the legend above the two bands of visualization, but no new line appears. I can keep clicking on the term with the apostrophe, and it will keep getting added to the legend, so that I can fill up the legend with multiple instances of the same term, but I don't get any trend lines out of it.

**Comment by sgsinclair** [comment]
Thanks for the bug report! I've done a quick fix though I should probably circle back and address the core issue of apostrophes in the DOM queries.

https://github.com/sgsinclair/Voyant/commit/8a7155f3080bae269e63631160e5402e83d56385

There should be a new build uploaded this week.
