### ISSUE TITLE
How can I restrict path traversal on our Voyant Server

### ISSUE THREAD

**Issue by soneal4** [sgsinclair/VoyantServer#24]
We are currently running a Voyant Server using Apache Tomcat 8.5.23. Our information security team alerted us to the fact that the server is vulnerable to path traversal. I noticed that https://voyant-tools.org doesn't have that problem. Can you advise us on some best practices to make sure our instance of Voyant is more secure? Thanks for your help

**Comment by sgsinclair** [comment]
Can you say more about your setup? The hosted version has nginx that proxies for Tomcat and both have root web directories that you can't traverse upwards. I'd assume the built-in Jetty server works this way too. Have you confirmed that unwanted files are accessible in your installation?

**Comment by soneal4** [comment]
Yes I've confirmed that /etc/passwd is accessible. 

Regarding our setup, we simply have voyant installed in the tomcat folder in the webapps/ROOT directory.

**Comment by sgsinclair** [comment]
Yikes. And do you have Apache proxying? I wonder if it's Tomcat that's serving the file or if it's something in front of it.

**Comment by soneal4** [comment]
I don't think we have Apache proxying. 

I tried installing VoyantServer on a vm without a tomcat installation, just running the jar file and I'm still able to traverse and get to /etc/passwd. Any suggestions as to how I could configure tomcat or httpd to block this?

**Comment by LiberalArtist** [comment]
I am trying to reproduce this on our VoyantServer installation and haven't managed to so far. @soneal4, are you just traversing upwards by putting `..` elements in the url path, or something more complicated? And may I ask what version you are using? I have been trying with v. 2.3 (M2) on Ubuntu so far, but will continue trying with other configurations.

**Comment by soneal4** [comment]
https://voyant.ace.fordham.edu/trombone?retrieveResourceId=../../../../../../../../../etc/passwd-&tool=resource.StoredResource&outputFormat=text

**Comment by soneal4** [comment]
I've been able to reproduce this in version 2.4

**Comment by LiberalArtist** [comment]
Thanks. Passing a query parameter like that, I can also reproduce using Voyant v. 2.3 (M2).

**Comment by soneal4** [comment]
I tried to do the same to https://voyant-tools.org and I am unable to

https://voyant-tools.org/trombone?retrieveResourceId=../../../../../../../../../etc/passwd-&tool=resource.StoredResource&outputFormat=text

**Comment by soneal4** [comment]
What would be the best way to go about fixing this issue?

**Comment by sgsinclair** [comment]
The URL helps as it shows me that it's the backend code being too permissive, not the sever. I'll try to patch this asap. I suspect my server is set up without passwords (only ssh keys). In the short-term you could run tomcat or jetty as a user that doesn't have read permissions to that file, but of course a more robust fix is needed.

**Comment by sgsinclair** [comment]
Btw I'm deleting the url in the comment thread.

**Comment by sgsinclair** [comment]
I think I've [fixed the vulnerability](https://github.com/sgsinclair/trombone/commit/7e3dc054775f94070962ceacb4b5b3a3f54725d7) and posted a [new release](https://github.com/sgsinclair/VoyantServer/releases/latest). Could you please try and let me know?

**Comment by LiberalArtist** [comment]
This appears to be working for me. Thanks for the quick patch!

If anyone is looking for a test url that's a bit more system-independent than `/etc/passwd`, assuming you are running from the default directory structure, http://localhost:8888/trombone?retrieveResourceId=../../../README.md&tool=resource.StoredResource&outputFormat=text will produce the readme file (contained in a JSON object) in versions affected by the vulnerability and the exception "An attempt was made to read a store string that that does not exist" in the patched version.

**Comment by soneal4** [comment]
This is working for me as well. Thanks for your help

**Comment by sgsinclair** [comment]
Great, thanks so much @soneal4 for bringing this vulnerability to our attention and to @LiberalArtist for helping to diagnose and test!
