### ISSUE TITLE
Adding new corpora to Voyant

### ISSUE THREAD

**Issue by neelofarhassan** [sgsinclair/VoyantServer#27]
An excellent and versatile tool.

Voyant already have two corpora incorporated, Shakespeare's palys and Austen Novels. I want to add some new corpora to the tool (standalone version) which could be accessed using dropdown that appears using "Open" button . Seems like it is not just a matter of adding the paths to server-settings.txt. 
Any suggestions please?

**Comment by sgsinclair** [comment]
There was a bug that prevented the open_menu mechanism from working properly. It's fixed in the current code base, but we have yet to build a release with it. Gmail me at this user handle if you want a temporary build for testing, otherwise I hope to post a build by the weekend.

**Comment by neelofarhassan** [comment]
Hello,

I can wait till weekend for you to release it. If you doubt it could take
more time, it will be great if you could provide me with the test build.

Could you please also give me a hint how to add new datasets (corpora) in
Open Menu (Like two already provided).

Thanks,
Neelofar

**Comment by sgsinclair** [comment]
So for the open_menu configuration, the [latest release](https://github.com/sgsinclair/VoyantServer/releases/latest) should now work. You can:

1) create a new corpus as you normally would
2) note the corpus ID in the URL after you've created it
3) open server_settings.txt and edit the line open_menu:

> open_menu = PASTE_CORPUS_ID_HERE:ENTER_DESIRED_LABEL_HERE

In other words corpus ID and label separated by a colon, and multiple entries separated by a semi-colon. Please let me know if you have any difficulties!

**Comment by neelofarhassan** [comment]
Thanks for the latest release and fixes. I still couldn't add a corpus in "Open Menu". As soon as I add anything against "open_menu = " in server_settings.txt, Open menu button stops working. It doesn't show any error message, but doesn't open any corpus as well (not even shakespeare or Austin). I am not very confident if I am following the correct steps. Here they are for your kind review

1. Download and unzip latest release (source code)
2. Add trombone classes
3. Add data and _app directory. The data directory already contains "Shakespeare and Aunstin" corpora. The directory contains 4 sub-directoriers : corpora, Lucene, Object_storage, stored_document_storage. _app directory contains web related code. 
4. Build the project using ant. The build will create a new directory "dist", having VoyantServer.jar, data, _app, server_settings.txt and other files/directories. VoyantServer.jar will start the server window, and finally initiate the web instance.
5. Using "Upload" button, add a new corpus in the web version. Note the corpus Id from the URL
6. Open server_settings.txt under the main project directory and edit the line Open_menu
open_menu = Corpus_ID:label;Austin:austin;Shakespeare:Shakespeare's Plays (I tried by removing spaces, removing id/label pair for already existing corpora etc.). 
7. Copy "data" directory from "dist" and paste under the main directory (having build.xml).
8. Build the project again. A new "dist" will replace the older one with new server_settings.txt (having new corpora details) and "data" directory (having newly added corpora).
9. Run VoyantServer.jar.
10. On webpage, clink "Open" button. Nothing happens !!!!

I have noticed that just adding any thing to Open_Menu in server_settings.txt makes "Open" button not working. I tried it without adding any new corpora and  just adding this line to
open_menu = shakespeare:Shakespeare's Plays;austen:Austen's Novels

**Comment by sgsinclair** [comment]
Are you trying to get it to work in Eclipse or just trying to launch VoyantServer? You should be able to edit server_settings.txt and then just double-click on VoyantServer.jar, that's it! If you want to create an instance of a server for others, have you seen this? https://github.com/sgsinclair/VoyantServer/wiki/Running-as-a-Shared-Server

**Comment by neelofarhassan** [comment]
I am not using eclipse but building the source using ant first (that
creates voyantserver.jar inside dist directory) instead of just launching
the server using voyantserver.jar.

You mean, I must launch the server, upload corpora, note url and add it to
server_settings.txt ( one that exists in the same directory as
voyantserver.jar?).

I will give it another try and let you know.

Thanks

**Comment by sgsinclair** [comment]
Can you say more about why you're building from ant?

**Comment by neelofarhassan** [comment]
I am working as part of a team that aims to find useful tools for Humanities and Social Sciences researchers. Voyant is being selected as one of the most versatile, handy and useful tool for research. My current aim is to add some useful datasets to voyant, however, I could be given more tasks in the future based on researchers requirements. That is why I want to explore the code of the application instead of just running it using Jar.

Even if I do not build the source code and launch the server directly using VoyantServer.jar (VoyantServer2_4-M5.zip), upload a document (pdf), edit Open_Menu using the ID that appears in URL and relaunch VoyantServer using jar, "Open" button doesn't work. It does nothing. I am testing it in Chrome Version 66.0.3359.139 and Firefox Quantum 59.0.3.

open_menu = b9985e0678aa084f99a87ce2d82c13b7:Thesis
I tried this one too
open_menu = shakespeare:Shakespeare's Plays;austen:Austen's Novels

Attached is the screenshot showing an error message in browser console. It only appears if open_menu is given some value in server-settings.txt

![browser-error-open-menu-chrome](https://user-images.githubusercontent.com/18094246/39735209-e33ce140-52bd-11e8-9d74-644ce4774a41.png)
![browser-error-open-menu-mozilla](https://user-images.githubusercontent.com/18094246/39735333-7ce0b646-52be-11e8-92dd-fcd9a54679c0.png)

**Comment by neelofarhassan** [comment]
Hello sgsinclair,

Are you able to reproduce it or is it something associated with my settings or browser? Any help would be highly appreciated.

**Comment by sgsinclair** [comment]
Very strange. I tried in Chrome and Firefox and it seems to work fine. I've posted a [temporary low-res video](https://www.dropbox.com/s/i7d9bmvh0ym7cex/voyantmenu.mp4?dl=0) to walk through the steps. Maybe try restarting the browser after saving the server-settings in case there's a cache issue.

**Comment by neelofarhassan** [comment]
Thanks for posting the video showing all the steps. It works perfectly on Mac with safari as browser (I haven't tried on other browsers with Mac), however, it doesn't work with Chrome or Mozilla on windows. I haven't tried it on any browser in linux yet.

**Comment by neelofarhassan** [comment]
May be this video would help. 
https://www.dropbox.com/s/qqnn49m5m6gv9mq/voyant-firefox-windows.avi?dl=0

**Comment by sgsinclair** [comment]
Thanks. I loaned my windows machine, but I'll test and fix as soon as I'm able.

**Comment by ajmacdonald** [comment]
Hello @neelofarhassan 
Looking at the video you posted, I notice that you're using an older version of Voyant/VoyantServer. The error message you receive references `replaceStoreItemsFromDefinition`, however [this code has been changed](https://github.com/sgsinclair/Voyant/commit/4200a49c0b6a81c29742a76a67733380e287a20f#diff-ea72fb34139b17ac0158ff68c8b6cef8L11252). Can you please retry with the latest release and let me know if the problem persists?

**Comment by neelofarhassan** [comment]
Hello @ajmacdonald 

Sorry for late reply. I wanted to test it fully on my office machine before making any comment. I have double checked that I am using the latest version of Voyant and sort of identified the problem as well. The error I reported do not trigger if I run firefox/chrome in private mode. I have no content/add blocker pluggins installed on my browsers.

**Comment by ajmacdonald** [comment]
@neelofarhassan if you are using the most recent release but are still seeing a reference to `replaceStoreItemsFromDefinition` in the error message, then you may need to clear your browser cache. This might explain why you don't see it in private mode.

**Comment by neelofarhassan** [comment]
Thanks @sgsinclair and @ajmacdonald . Clearing the cache worked.
