### ISSUE TITLE
download link does not work

### ISSUE THREAD

**Issue by lingdp** [sgsinclair/VoyantServer#3]
Hi,

I tried to download VoyantServer from the link you provide on the voyant-tools website (http://docs.voyant-tools.org/resources/run-your-own/voyant-server/), but it does not work (there's a "file not found" error instead). 

Best

**Comment by lingdp** [comment]
Oh, sorry, forgot to state the link that doesn't work. Here you go:

 http://dev.voyant-tools.org/downloads/current/VoyantServer.zip

**Comment by sgsinclair** [comment]
Thanks, the link should work now. Just in case this isn't clear: that link is for Voyant 1 (the "current" version), Voyant 2 (beta) is available here: https://github.com/sgsinclair/VoyantServer/releases

**Comment by lingdp** [comment]
yep, works. thank you very much!
