### ISSUE TITLE
Feature Request: Voyant Concept Map

### ISSUE THREAD

**Issue by ghost** [sgsinclair/VoyantServer#33]
Greetings,

I am curious if the voyant system can generate concept maps?
It seems that the data exists, but the visualization requires work.
Does there exist information on connections between keywords?

Thank you,
Rob

**Comment by sgsinclair** [comment]
Hi Rob, the short answer is no, there's no real support for language-specific analysis like semantic linking. There are bits and pieces buried in the code that support various mini-experiments that have been attempted, but the current architecture can't really handle such computationally demanding requests on an open server.

For what it's worth, the plan is to support a type of notebook environment where some calls could be made to external APIs for things like concept maps, and then mixed in with existing Voyant tools and other visualizations. But not in the short-term :).

**Comment by ghost** [comment]
EDIT:
I was able to get the IntelliJ Idea debugger functioning.

##

Hello Stéfan,

I am interested in developing this feature further. Do you have any tips from your experience for setting up the debugger?

Thank you,
Rob
