### ISSUE TITLE
Tomcat: VoyantServer demo data (Shakespeare and Austen) does not exist. 

### ISSUE THREAD

**Issue by PieterLabuschagne** [sgsinclair/VoyantServer#35]
Good day,

Please assist with Tomcat configuration for data not loading.

Server specifications:
CentOS 7.5
Java 1.8.0_152
Tomcat 9.0.1
VoyantServer 2.4 (M36)

VoyantServer Setup:
Copied _app to /opt/tomcat/webapps and renamed to voyant.
Can access via: http://v-sdlr-lnx3.nwu.ac.za:8080/voyant/

When I select Open and choose a corpus:
Error: Failed attempt to create a Corpus
A corpus was specified but does not exist, could not be migrated and could not be recreated: shakespeare ... more.

Where must I put the data folder or how can I configure the data_directory? Since I'm not starting the VoyantServer from the .jar file the server-settings.txt is not used. Is there a way to set server-settings for Tomca? I would like the data folder to be located at /data/voyant on my server.

Thank you.

**Comment by sgsinclair** [comment]
You need to determine (or set) where your temporary Tomcat data directory is and then copy the contents of "data" from the original zip folder to that location – that will allow your Voyant to find and migrate the built-in Shakespeare and Austen directories. Please let me know how it goes.

**Comment by PieterLabuschagne** [comment]
Hi sgsinclair,

Thank you for your help. It's working now. My mistake was I copied the whole "data" folder to the temp Tomcat folder instead of its contents.

Kind regards
Pieter
