### ISSUE TITLE
VoyantServer eats memory and spits out crashes

### ISSUE THREAD

**Issue by titaniumbones** [sgsinclair/VoyantServer#4]
Hi,

i'm trying to run the latest beta on a perhaps-underpowered ubuntu server (only 4gb memory, I think) using oracle java 8. After a few minutes of intense usage -- say, uploading of 3-4 corpora by my students, the server will eat up all my memory and eventually crash.  Maybe there's a garbage collection problem? Happy to try some debugging ,though I know nothing about Java, so may not be very helpful.  Thanks!
Matt

**Comment by sgsinclair** [comment]
Thanks Matt. Are you using the VoyantServer UI to launch the server or the command line? If the latter, are you setting the memory to something a bit higher? Having asked that, there's definitely a leak somewhere and I'll definitely try to track it down.

**Comment by titaniumbones** [comment]
Hi,

I am doing it from the command line but know really nothing about java.
I have just tried again with

-Xmx2g  -Xms2g

-- I don't know if those are good values or not, but I will see how it
goes over the next little while!  Thanks for the response!

**Comment by sgsinclair** [comment]
Yes, I was going to suggest the -Xmx argument (and 2g is a decent choice on a 4g machine). Please let me know if you still encounter difficulties.

**Comment by titaniumbones** [comment]
So far, CPU usage seems much more stable, but that might be because
everyone's given up after a rough week! I will know more later this week.

**Comment by titaniumbones** [comment]
hi again -- gearing up for another run of the same class, starting in January. Was wondering how stable beta.voyant-tools.org is lately, and whether it's appropriate to try to upload new corpora there. Have not settled on an assignment yet but would like to provide students with 2 or 3 choices of corpus to analyze; running on my own underpowered server was difficult last summer, if it's possible to use beta.voyant-tools.org that would be great.

**Comment by sgsinclair** [comment]
Were you running V1 or V2 on your own server last summer? For some things V2 is much more efficient (then again, more efficient means the possibility of larger corpora, which can slow things back down).

I was hoping to do a full update before the end of the year (V2 would be hosted at voyant-tools.org) but a few things have conspired to slow down that timeline. Officially the hosted beta version shouldn't be used when persistent URLs are important (they may or may not persist), but if I have a timeframe from you, I can be careful.

**Comment by shgregg** [comment]
Sounds like the same thing for me. I've been trying to get the onlin version to work with a relaively large text file (173mb) but it sits there buffering (no probs with other files). I tried this version it chucks it out. Error -> lack of Java heapspace but my Xmx already at max.

**Comment by sgsinclair** [comment]
There was a bug in the language detection module that was causing problems for larger documents, it should now be fixed in [M9](https://github.com/sgsinclair/VoyantServer/releases/tag/2.0.1-M9).

Upload speeds are still slow but that's an upstream issue, it shouldn't affect standalone installations.

I'll close this for now, but please do reopen if need be.

https://github.com/sgsinclair/trombone/commit/a37df7d156a9e135eaa1433afdf43128445ba635

**Comment by titaniumbones** [comment]
@sgsinclair i would love ot upgrade, but don't want to screw over the students who have successfully uploaded corpora already on my server, which is running M8. Is there a way to import corpora into a new version? 

(even better -- would it be possible to add corpora to the initial multiple choice list or corpora that Voyant provides users on the splash screen?)

Thanks as always,
Matt

**Comment by sgsinclair** [comment]
M8 and M9 should be completely compatible, so a few possibilities, all assuming you first stop M8:
1. copy M8/data to M9/data (replace existing M9/data)
2. edit M9/server-settings.txt to point `data_directory` to absolute path of M8/data
3. copy or move M8/data elsewhere, edit M9/server-settings.txt to point `data_directory` to new absolute path

1) is probably easiest, 3) is probably best for future updates
