### ISSUE TITLE
Unable to compile class for JSP

### ISSUE THREAD

**Issue by jsmm** [sgsinclair/VoyantServer#5]
Hello,

VoyantServer is no longer running in my machine, OS X 10.11.4. I wonder if it has stopped working after upgrading to jdk1.8.0_51.jdk. 
I have downloaded version 2.1 M1 since, but it does give the same error. Thanks for your help,

> HTTP ERROR 500
> Problem accessing /. Reason:
>     Server Error
> Caused by:
> org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP
> PWC6199: Generated servlet error:
> The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files
>     at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:123)
>     at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:296)
>     at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:376)
>     at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
>     at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
>     at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
>     at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
>     at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
>     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
>     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>     at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
>     at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
>     at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:585)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
>     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
>     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>     at org.eclipse.jetty.server.Server.handle(Server.java:485)
>     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
>     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
>     at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by sgsinclair** [comment]
Thanks for the report. This is perplexing since the apparent error "The type java.io.ObjectInputStream cannot be resolved" shouldn't be an issue – that's a core class of the Java distribution. But someone else reported the same problem. I suspect it's something to do with the embedded Jetty server, but I'll need to keep digging.

**Comment by sgsinclair** [comment]
@jsmm could you please open the data directory and remove all the jetty-0.0.0.0-8888\* subdirectories, and then try again?

**Comment by jsmm** [comment]
@sgsinclair Same result after deleting those files; even after deleting the app and unzipping a newly downloaded one. Jar Launcher.app is at version 15.0.1. Thanks again.

> **\* Starting Voyant Server – Web page will open automatically when ready ***
> 
> Using Free AdminPort=34000
> Server Starting
> 2016-04-26 01:44:10.797:INFO::main: Logging initialized @161ms
> Jetty Version: 9.2.z-SNAPSHOT
> http://*:8888
> Jetty starting up ... please wait
> 2016-04-26 01:44:10.928:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
> 2016-04-26 01:44:11.813:WARN:oejs.SecurityHandler:main: ServletContext@o.e.j.w.WebAppContext@17550481{/,file:/Users/almi/Documents/Corpus_software/VoyantServer2_1-M1/_app/,STARTING} has uncovered http methods for path: /
> 2016-04-26 01:44:12.121:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@17550481{/,file:/Users/almi/Documents/Corpus_software/VoyantServer2_1-M1/_app/,AVAILABLE}
> 2016-04-26 01:44:12.168:INFO:oejs.ServerConnector:main: Started ServerConnector@16f7c8c1{HTTP/1.1}{0.0.0.0:8888}
> 2016-04-26 01:44:12.169:INFO:oejs.Server:main: Started @1588ms
> ... Jetty has started.
> ERROR: Compilation error
> org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
>   at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:372)
>   at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:367)
>   at org.apache.jasper.compiler.JDTJavaCompiler$1.findType(JDTJavaCompiler.java:324)
>   at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:102)
>   at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
>   at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
>   at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:168)
>   at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:2376)
>   at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1004)
>   at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1219)
>   at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:528)
>   at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:759)
>   at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:464)
>   at org.apache.jasper.compiler.JDTJavaCompiler.compile(JDTJavaCompiler.java:503)
>   at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:368)
>   at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
>   at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
>   at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
>   at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
>   at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
>   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>   at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
>   at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
>   at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:585)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
>   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>   at org.eclipse.jetty.server.Server.handle(Server.java:485)
>   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
>   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
>   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
>   at java.lang.Thread.run(Thread.java:745)
> ERROR: Error compiling file: /Users/almi/Documents/Corpus_software/VoyantServer2_1-M1/data/jetty-0.0.0.0-8888-_app-_-any-7690507070701799226.dir/jsp/org/apache/jsp/index_jsp.java
> 2016-04-26 01:44:13.330:WARN:oejs.ServletHandler:qtp834600351-16: 
> org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP||PWC6199: Generated servlet error:|The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files||
>   at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:123)
>   at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:296)
>   at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:376)
>   at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
>   at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
>   at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
>   at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
>   at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
>   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>   at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
>   at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
>   at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:585)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
>   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>   at org.eclipse.jetty.server.Server.handle(Server.java:485)
>   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
>   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
>   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
>   at java.lang.Thread.run(Thread.java:745)

**Comment by sgsinclair** [comment]
Could you please try this new build to see if it works any better? https://github.com/sgsinclair/VoyantServer/releases/download/2.1.0-M2/VoyantServer.zip

If that doesn't help things, then I'll need to keep fiddling with a bundled JSP compiler…

**Comment by jsmm** [comment]
Thank you, Stéfan.
2.1.0-M2 works without problems!

**Comment by sgsinclair** [comment]
fantastic, thanks for confirming!

**Comment by karlli1976** [comment]
I met this problem as well. 

OS:
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

VoyantServer2_4-M7

Fortunately following your guide (remove all the jetty-0.0.0.0-8888* subdirectories), and it works :)

Thanks.
