### ISSUE TITLE
create mechanism for preventing additional corpora from being created

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/VoyantServer#6]

**Comment by mbwolff** [comment]
Hi Stefan. I apologize in advance if this is not the right forum for a question. Is it possible to upload a corpus and then tweak VoyantServer so that a user can choose the corpus as a pre-defined option (along with Austen and Shakespeare)?

**Comment by sgsinclair** [comment]
Not currently (though that was possible with a previous version). Should be relatively quick to restore. Are you in a hurry?

**Comment by mbwolff** [comment]
No big hurry, but if it could be restored by the end of the month that would be great. I found quick workaround by renaming an uploaded corpus in data/trombone4_2/corpora and then modifying metadata.xml. I haven’t found a way to add the menu option though.

> On Aug 8, 2016, at 3:15 PM, Stéfan Sinclair notifications@github.com wrote:
> 
> Not currently (though that was possible with a previous version). Should be relatively quick to restore. Are you in a hurry?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Mark B. Wolff, Ph.D.

http://markwolff.name/

**Comment by sgsinclair** [comment]
That's a very resourceful workaround :).

I'm hoping a more robust solution is now working in the latest preview release [2.2 M1](https://github.com/sgsinclair/VoyantServer/releases/tag/2.2.0-M1), can you give it a spin and let me know? Look in particular at the bottom of the [server_settings.txt](https://github.com/sgsinclair/VoyantServer/blob/master/server-settings.txt#L51) file for instructions.

BTW, if you want friendlier corpus IDs you can create a symbolic link in the corpora folder, Voyant has various mechanisms for handling things from there. For instance on a unix-based system from within the corpora folder:

```
ln -s verylonguglyid niceid
```

I'm going to keep this ticket open since it's for something else, but feel free to post here again or create a new ticket if it's not working for you.

**Comment by mbwolff** [comment]
Thanks Stefan! That was quick. I edited the string in the server-settings.txt file per your instructions but unfortunately I could not start the server. Here’s the string I added to the file:

open_menu = shakespeare:Shakespeare's Plays;austen:Austen's Novels;hilltops:Hilltops

And here’s the error message:

Error: Could not find or load main class "-Dorg.voyanttools.voyant.openmenu=shakespeare:Shakespeare's Plays;austen:Austen's Novels;hilltops:Hilltops”

If I use the default for the drop-down menu, it works but the user has to type ‘hilltops’ when prompted to choose a corpus.

I also renamed the corpus directory ‘hilltops’ and edited the metadata.xml file as I had done before.

> On Aug 10, 2016, at 11:26 AM, Stéfan Sinclair notifications@github.com wrote:
> 
> That's a very resourceful workaround :).
> 
> I'm hoping a more robust solution is now working in the latest preview release 2.2 M1, can you give it a spin and let me know? Look in particular at the bottom of the server_settings.txt file for instructions.
> 
> BTW, if you want friendlier corpus IDs you can create a symbolic link in the corpora folder, Voyant has various mechanisms for handling things from there. For instance on a unix-based system from within the corpora folder:
> 
> ln -s verylonguglyid niceid
> 
> I'm going to keep this ticket open since it's for something else, but feel free to post here again or create a new ticket if it's not working for you.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Mark B. Wolff, Ph.D.

http://markwolff.name/

**Comment by sgsinclair** [comment]
Ack, I hadn't tested sufficiently with different values and situations, sorry. Can you please try re-downloading [2.2M1](https://github.com/sgsinclair/VoyantServer/releases/tag/2.2.0-M1) and let me know?

**Comment by mbwolff** [comment]
Hi Stefan. I tried the latest version of 2.2M1 and am still having problems. Here is the parameter in the server-settings.txt file (I removed the apostrophes because I thought they were the culprits):

open_menu = shakespeare:Shakespeares Plays;austen:Austens Novels;hilltops:Hilltops

After loading the main page I looked at the source and saw this error message for the Javascript pull-down menu:

Unexpected identifier 'shakespeare'. Expected '}' to end a object literal.

I hope this helps. I’d send you the link for my instance of Voyant Server but the port is not open beyond our campus.

Thanks!

mw

> On Aug 10, 2016, at 2:44 PM, Stéfan Sinclair notifications@github.com wrote:
> 
> Ack, I hadn't tested sufficiently with different values and situations, sorry. Can you please try re-downloading 2.2M1 and let me know?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Mark B. Wolff, Ph.D.

http://markwolff.name/

**Comment by sgsinclair** [comment]
Hmm, strange, it seems to work fine for me using that exact value. Can you describe your environment and how you're running VoyantServer? Also can you tell me what you see on the line with openMenu in the source code of the web page that opens when you first launch VoyantServer?

![2016-08-10 21-16-50](https://cloud.githubusercontent.com/assets/355388/17576367/02093a7e-5f40-11e6-9274-cc4a94ad21c4.png)

**Comment by mbwolff** [comment]
I’m running VoyantServer on Ubuntu 16.04 LTS. I have the problem with the pull-down menu on Safari and Chrome (I have not checked Firefox). When I use developer tools with Chrome I get this error message:

bumppo.hartwick.edu/:58 Uncaught SyntaxError: Unexpected identifier

When I inspect the Javascript on the first page in Chrome, it looks like this:

54 config: {
55          baseUrl: '//bumppo.hartwick.edu:8888/',
56          version: '2.2',
57          build: 'M1',
58          openMenu: ""shakespeare:Shakespeares Plays;austen:Austens Novels;hilltops:Hilltops""
59      },

(I wonder about the double double quotes in line 58: they show up when I load the main page into Safari.)

> On Aug 10, 2016, at 9:21 PM, Stéfan Sinclair notifications@github.com wrote:
> 
> Hmm, strange, it seems to work fine for me using that exact value. Can you describe your environment and how you're running VoyantServer? Also can you tell me what you see on the line with openMenu in the source code of the web page that opens when you first launch VoyantServer?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Mark B. Wolff, Ph.D.

http://markwolff.name/

**Comment by sgsinclair** [comment]
That's very helpful, thanks. I'm not quite sure why, but it seems like system parameters are being treated differently on Ubuntu. I'm not able to test directly, but I've made a tweak that will hopefully resolve the issue. Could you please [try again](https://github.com/sgsinclair/VoyantServer/releases/tag/2.2.0-M1) and let me know?

**Comment by mbwolff** [comment]
I think it works now. I'm on a bus headed to NYC and installed/configured/started the server from my smartphone, so I can't  reload the data (well maybe I could but I hate typing on tiny touch screens). I have managed to customize the drop-down menu. I return home Saturday and will test the server more thoroughly. 

Thanks for your help!

mw

**Comment by sgsinclair** [comment]
Great, thanks for your perseverence and help, let me know if there's a problem.

**Comment by mbwolff** [comment]
Hi Stéfan. VoyantServer works fine now with my data. It’s accessible at bumppo.hartwick.edu:8888. Thanks again for all your help.

> On Aug 11, 2016, at 12:33 PM, Stéfan Sinclair notifications@github.com wrote:
> 
> Great, thanks for your perseverence and help, let me know if there's a problem.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Mark B. Wolff, Ph.D.

http://markwolff.name/

**Comment by sgsinclair** [comment]
This issue was initially about having Voyant not accept new documents and then morphed into specifying the open menu contents (which is resolved). As of [now](https://github.com/sgsinclair/Voyant/issues/349), it's also possible to make VoyantServer not allow new documents to be added to a corpus. This isn't yet in any release, but it will be in 2.2 (no milestone) which should be ready within a week or two.

**Comment by sgsinclair** [comment]
P.S. this is now possible with a value in [server-settings.txt](https://github.com/sgsinclair/VoyantServer/blob/452a1573124ab8188d4ccd7d54807a971f9e1e7c/server-settings.txt#L68):

**Comment by mbwolff** [comment]
Thanks Stéfan!

mw

> On Mar 13, 2017, at 12:47 PM, Stéfan Sinclair <notifications@github.com> wrote:
> 
> This issue was initially about having Voyant not accept new documents and then morphed into specifying the open menu contents (which is resolved). As of now, it's also possible to make VoyantServer not allow new documents to be added to a corpus. This isn't yet in any release, but it will be in 2.2 (no milestone) which should be ready within a week or two.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Mark B. Wolff, Ph.D.

http://markwolff.name/
