### ISSUE TITLE
server-settings.txt has conflicting content

### ISSUE THREAD

**Issue by triplingual** [sgsinclair/VoyantServer#7]
Just downloaded the 2.1 zip, and found `server-settings.txt` to have an internal conflict, or possibly just an unreliable narrator.
Before the line with the IP restriction, there is the description
`# VoyantServer is also a convenient way to host an instance of Voyant Tools that you might`
`# want to have more widely accessible, in which case you should comment out this line or remove`
`# the value.`
But the IP line is already commented out
`# host = 127.0.0.1`

**Comment by triplingual** [comment]
(Meant to say that I would change, since it's so minor, but it's a UX question more than anything, and I don't know which you want as the default, restricted or open.)

**Comment by sgsinclair** [comment]
I like unreliable narrator theory :) 481af2369b32180a03cd412a81cc612bcc3e2ecc
