### ISSUE TITLE
Non-empty data directory already exists dès le début

### ISSUE THREAD

**Issue by triplingual** [sgsinclair/VoyantServer#8]
Similar to #7, `server-settings.txt` instructs the user to create an empty `data` directory to have a non-tmp space for files or to set a value for `data_directory` in the file. But in the d/l I made today, there's already a `data` directory at the same level as `VoyantServer.jar`.
Contents
`drwxrwxr-x 3 ubuntu ubuntu 4096 Jul 12 17:36 jetty-0.0.0.0-8888-_app-_-any-228982559801084515.dir`
`drwxrwxr-x 3 ubuntu ubuntu 4096 Jul 12 17:36 jetty-0.0.0.0-8888-_app-_-any-4377742236646231959.dir`
`drwxrwxr-x 3 ubuntu ubuntu 4096 Jul 12 17:36 jetty-0.0.0.0-8888-_app-_-any-8231381278420879704.dir`
`drwxrwxr-x 4 ubuntu ubuntu 4096 Jul 12 17:36 tmp.voyant.uploads`
`drwxrwxr-x 6 ubuntu ubuntu 4096 Jul 12 17:36 trombone4_2`

**Comment by sgsinclair** [comment]
Thanks (very belatedly) for pointing this out. I'll update it to be more accurate, the included data directory can be used for access to the built-in corpora, can be emptied for a non-tmp blank slate, or can be removed to default to a tmp directory.

**Comment by sgsinclair** [comment]
f6336e0d9f156a955051404e6966267b49c69e8b
